defaults: &defaults
  docker:
  - image: rajashrik/de-infrabox

version: 2
jobs:
 build:
    <<: *defaults
    steps:
    - checkout
    - run: ./scripts/create_tf_state_bucket.sh $TRAINING_COHORT_TEST


workflows:
  version: 2
  build:
    jobs:
     - build
