defaults: &defaults
  docker:
  - image: rajashrik/de-infrabox-v1
  working_directory: /home/circleci/project

version: 2
jobs:
 build:
    <<: *defaults
    steps:
    - checkout
    - run:
        command: source /okta_venv/bin/activate;
                ./scripts/create_tf_state_bucket.sh $TRAINING_COHORT

workflows:
  version: 2
  build:
    jobs:
     - build
