defaults: &defaults
  docker:
  - image: circleci/openjdk:8-jdk
  working_directory: /home/circleci/project

version: 2
jobs:
  build-test-environment:
    <<: *defaults
    steps:
    - checkout
    - run:
        command: echo "Hello world"
workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build-test-environment:
        type: approval
        filters:
          branches:
            only:
            - bangalore-april-2019-test
            - master
