defaults: &defaults
  docker:
  - image: circleci/openjdk:8-jdk
  working_directory: /home/circleci/project

version: 2
jobs:
 build:
    <<: *defaults
    steps:
    - checkout
    - run:
        command: sudo apt-get install docker
    - setup_remote_docker
    - run:
        command: docker-compose run --rm infrabox
    - run:
        command: exit

workflows:
  version: 2
  build:
    jobs:
     - build
